syntax = "proto3";

package fjarm.users.v1;

import "fjarm/users/v1/user.proto";

option go_package = "github.com/fjarm/fjarm/api/pkg/fjarm/users/v1";
option java_multiple_files = true;
option java_outer_classname = "GetUserResponseProto";
option java_package = "xyz.fjarm.users.v1";

// GetUserResponse describes the result of attempting an RPC to retrieve a user.
message GetUserResponse {
  // The user and related details. This field is not annotated as with `[(buf.validate.field).required = true];` because
  // the `GetUserRequest` supports sending an ETag. If the client ETag matches the server ETag and the client
  // representation of the `User` is up to date, then this field can be empty.
  optional fjarm.users.v1.User user = 1;
}
