load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "authentication",
    srcs = [
        "connect_rpc_handler.go",
        "connect_rpc_handler_create_session.go",
    ],
    importpath = "github.com/fjarm/fjarm/api/internal/authentication/v1/internal/authentication",
    visibility = ["//api/internal/authentication/v1:__subpackages__"],
    deps = [
        "@build_buf_gen_go_fjarm_fjarm_connectrpc_go//fjarm/authentication/v1/authenticationv1connect",
        "@build_buf_gen_go_fjarm_fjarm_protocolbuffers_go//fjarm/authentication/v1:authentication",
        "@build_buf_go_protovalidate//:protovalidate",
    ],
)
