name: Android unit test PR checks
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
    paths:
      - 'android/**.kt'
      - 'android/**.kts'
      - 'android/**'
      - 'build-logic/**'
      - 'gradle/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'settings.gradle.kts'
  pull_request:
    paths:
      - 'android/**.kt'
      - 'android/**.kts'
      - 'android/**'
      - 'build-logic/**'
      - 'gradle/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'settings.gradle.kts'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }} # Don't cancel workflow runs on main branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4
        name: Checkout repo

      - uses: actions/setup-java@v5
        name: Set up JDK 21
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - uses: gradle/actions/setup-gradle@v5
        name: Set up Gradle

      - name: Build all tasks
        run: |
          ./gradlew build

      - name: Run all unit tests
        run: |
          ./gradlew testDebugUnitTest
