name: Buf Schema Registry push
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4
        name: Checkout repo
      # Install the `buf` CLI, lint and format files, detect breaking changes, and push the latest schema
      - uses: bufbuild/buf-action@v1
        name: Run Buf validation and push latest schema
        with:
          version: "1.46.0"
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}
          lint: true
          format: false
          breaking: true
          breaking_against: "https://github.com/fjarm/fjarm.git#branch=main"
          push: true
          push_disable_create: true
