name: Buf PR checks
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
    paths:
      - "proto/**"
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
    paths:
      - "proto/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4
        name: Checkout repo
      # Install the `buf` CLI
      - uses: bufbuild/buf-action@v1
        name: Run Buf validation
        with:
          version: "1.46.0"
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}
          lint: true
          format: true
          breaking: true
          pr_comment: true
          push: false
          push_disable_create: true
