name: DockerHub push
on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Bazel oci_push target to build and push'
        required: true
        type: choice
        options:
          - helloworld:helloworld_push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4
        name: Checkout repo
      # Log in to the `docker` CLI
      - uses: docker/login-action@v3
        name: Log in to Docker CLI
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: bazel-contrib/setup-bazel@0.12.1
        name: Install Bazel CLI
        with:
          # Avoid downloading Bazel every time
          bazelisk-cache: true
          bazelisk-version: 1.x
          # Share a single disk cache across workflows
          disk-cache: true
          # Enable external repositories caches
          external-cache: true
          # Store a single repository cache
          repository-cache: true
      - name: Build all targets under api
        run: |
          bazel build //api/...
      - name: Run oci_push target
        run: |
          bazel run //api/deployment/${{ inputs.module }} --config=release
